# Generated by Django 5.1 on 2024-09-22 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=16)),
                ('descripcion', models.TextField()),
                ('sigla_asignatura', models.CharField(max_length=8)),
                ('paralelo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UnidadAcademica',
            fields=[
                ('id_unidad_academica', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64)),
                ('presupuesto', models.IntegerField()),
                ('gasto', models.IntegerField()),
                ('emplazamiento', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=16)),
                ('rol', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id_cotizacion', models.AutoField(primary_key=True, serialize=False)),
                ('es_principal', models.BooleanField()),
                ('monto', models.IntegerField()),
                ('tipo', models.CharField(choices=[('Solo traslado', 'Sólo traslado'), ('Solo colacion', 'Sólo colación'), ('Traslado y colacion', 'Traslado y colaciones')], max_length=50)),
                ('archivo', models.FileField(upload_to='cotizaciones/')),
                ('estado', models.CharField(max_length=16)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.solicitud')),
            ],
        ),
        migrations.AddField(
            model_name='solicitud',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usuario'),
        ),
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id_reembolso', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField()),
                ('fecha_pago', models.DateField()),
                ('estado', models.CharField(max_length=16)),
                ('fecha_visita', models.DateField()),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.solicitud')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id_visita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('semestre', models.CharField(max_length=5)),
                ('lugar', models.CharField(max_length=64)),
                ('profesor_encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usuario')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('rut', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.visita')),
            ],
        ),
    ]
