# Generated by Django 5.1 on 2024-10-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_campus_alter_solicitud_paralelo_edificio_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='nombre_empresa',
            field=models.CharField(default='NN', max_length=64),
        ),
    ]
